name: "CI CD Android"
on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

  workflow_dispatch:

jobs:
  unit_test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup local.properties
        env:
          FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
        run:
          echo FIREBASE_DATABASE_URL="$FIREBASE_DATABASE_URL" > ./local.properties

      - name: Run Test
        run: |
          ./gradlew test --stacktrace
  android_test:
    name: Run Instrumentation Test
    runs-on: macos-latest
    env:
      FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup local.properties
        env:
          FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
        run:
          echo FIREBASE_DATABASE_URL="$FIREBASE_DATABASE_URL" > ./local.properties

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  build:
    runs-on: ubuntu-latest
    needs: [ unit_test, android_test ]
    env:
      FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

#      - name: Decode Keystore
#        env:
#          ENCODED_STRING: ${{ secrets.KEYSTORE }}
#        run: |
#          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
#          mkdir "${TMP_KEYSTORE_FILE_PATH}"
#          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/github_user_keystore.jks
      - name: Gradle build
        env:
          FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
        run:
          echo FIREBASE_DATABASE_URL="$FIREBASE_DATABASE_URL" > ./local.properties
          ./gradlew app:bundleRelease --stacktrace

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-